n1 = input("digite algo aqui: ")
print(f'o tipo primitivo desse valor é', type(n1))
print("está espaçado?", n1.isspace())
print("é alfabetico?", n1.isalpha())
print("é um decimal? ", n1.isdecimal())
print("é um numerico?", n1.isnumeric())
print("é um alfanumerico?", n1.isalnum())
print("está em maiusculo?", n1.isupper())
print("está em minusculo?", n1.islower())
print("está capitalizado?", n1.istitle())